# Version du format de docker compose
version: '3'

# Définit les conteneurs que nous voulons créer
services:
# Conteneur MySQL
  mysql:
  # Informations liées au conteneur
    image: mysql:latest
    container_name: mysql
    # Informations pour l'environnement MySQL
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3000:3000"

# Conteneur PhpMyadmin
  phpmyadmin:
  # Informations liées au conteneur
    image: phpmyadmin:latest
    container_name: phpmyadmin
    # Informations pour l'environnement PhpMyadmin
    environment:
      # Permet de pouvoir définir des info de connexion
      PMA_ARBITRARY: 1
      # Adresse du serveur au quelle PhpMyadmin se connecte
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
      # Assure que MySQL est démarré avant PHPMyAdmin
    depends_on:
      - mysql